### ISSUE TITLE
Game Not Working

### ISSUE THREAD

**Issue by srbmaury** [panditsamik/Snake-Game#14]
![image](https://github.com/panditsamik/Snake-Game/assets/85755081/04333d25-7cb7-40d2-b687-0245f6e1c750)

**Comment by pathakharsh123** [comment]
@srbmaury  please assign me this issue

**Comment by srbmaury** [comment]
> @srbmaury please assign me this issue

@panditsamik is the owner of the repo

**Comment by SumitVerma-coder** [comment]
@panditsamik please assign me this issue

**Comment by strange98350** [comment]
@panditsamik  please assign this issue to me
