### ISSUE TITLE
I can Add border to the Game Interface, also make the UI more visually Appealing

### ISSUE THREAD

**Issue by ayushsgit** [panditsamik/Snake-Game#3]

**Comment by ayushsgit** [comment]
I added the changes 
See them here : https://leafy-beignet-ba2a54.netlify.app/
If you like them i will do a PR

**Comment by panditsamik** [comment]
> I added the changes See them here : https://leafy-beignet-ba2a54.netlify.app/ If you like them i will do a PR

Yaa, it's nice. You can make a PR.
